/*!
* @file i2c\i2c.c
* @author D.Chikov
* @date 10/15/2020, 09:37:33
* @brief ...tbd...
*/


#include "i2c.h"


/*!
* 	 void i2c_init(I2CCom i2c)
* 
* 	...tbd...
* 	\param I2CCom i2c -...
* 	\return void -...
*/
void i2c_init(I2CCom i2c);

// for software i2C

/*!
* 	 void swi2c_configure(uint32_t gpio_sdc, uint32_t gpio_sda)
* 
* 	...tbd...
* 	\param uint32_t gpio_sdc -...
* 	\param uint32_t gpio_sda -...
* 	\return void -...
*/
void swi2c_configure(uint32_t gpio_sdc, uint32_t gpio_sda);


/*!
* 	 ResultError_t i2c_write(I2CCom i2c, uint8_t *pdata, uint32_t bytes)
* 
* 	...tbd...
* 	\param I2CCom i2c -...
* 	\param uint8_t *pdata -...
* 	\param uint32_t bytes -...
* 	\return ResultError_t -...
*/
ResultError_t i2c_write(I2CCom i2c, uint8_t *pdata, uint32_t bytes);

/*!
* 	 ResultError_t i2c_read(I2CCom i2c, uint8_t *pdata, uint32_t bytes)
* 
* 	...tbd...
* 	\param I2CCom i2c -...
* 	\param uint8_t *pdata -...
* 	\param uint32_t bytes -...
* 	\return ResultError_t -...
*/
ResultError_t i2c_read(I2CCom i2c, uint8_t *pdata, uint32_t bytes);

/*!
* 	 void i2c_ack(I2CCom i2c)
* 
* 	...tbd...
* 	\param I2CCom i2c -...
* 	\return void -...
*/
void i2c_ack(I2CCom i2c);

/*!
* 	 void i2c_nak(I2CCom i2c)
* 
* 	...tbd...
* 	\param I2CCom i2c -...
* 	\return void -...
*/
void i2c_nak(I2CCom i2c);
